# ════════════════════════════════════════════════════════════════════════════
#  Customer KYC API — Multi-stage Linux Docker build
#  Base images: mcr.microsoft.com/dotnet/sdk:10.0   (build)
#               mcr.microsoft.com/dotnet/aspnet:10.0 (runtime)
#
#  Linux compatibility objective:
#   - TDESEncrypt.dll is a managed .NET assembly → loads on Linux without wine/compat.
#   - No Windows-only packages are installed.
#   - Application runs as a non-root user.
# ════════════════════════════════════════════════════════════════════════════

# ── Stage 1: Build & Test ────────────────────────────────────────────────────
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /source

# Copy project files first for Docker layer caching on restore
COPY src/TDESEncrypt/TDESEncrypt.csproj                           src/TDESEncrypt/
COPY src/CustomerKyc.Api/CustomerKyc.Api.csproj                   src/CustomerKyc.Api/
COPY tests/CustomerKyc.Api.Tests/CustomerKyc.Api.Tests.csproj     tests/CustomerKyc.Api.Tests/
COPY CustomerKyc.Poc.slnx .
# Note: .NET 10 SDK uses the new .slnx format (XML-based solution file).
# .sln (legacy) is not generated by default in .NET 10.

RUN dotnet restore

# Copy all source code
COPY src/   src/
COPY tests/ tests/

# Build
RUN dotnet build -c Release --no-restore

# Run unit & integration tests (SQL-dependent integration tests are skipped via in-memory fake)
RUN dotnet test tests/CustomerKyc.Api.Tests/CustomerKyc.Api.Tests.csproj \
    --no-build -c Release \
    --logger "console;verbosity=normal"

# Publish application
RUN dotnet publish src/CustomerKyc.Api/CustomerKyc.Api.csproj \
    -c Release \
    --no-build \
    -o /app/publish

# ── Stage 2: Runtime ─────────────────────────────────────────────────────────
FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app

COPY --from=build /app/publish .

# Confirm TDESEncrypt.dll landed in the publish output (build-time assertion)
RUN test -f TDESEncrypt.dll && echo "TDESEncrypt.dll: present in image" \
    || (echo "TDESEncrypt.dll: MISSING from publish output" && exit 1)

# The official mcr.microsoft.com/dotnet/aspnet:10.0 image is Ubuntu-Chiseled
# (minimal — no adduser/useradd). It ships with a pre-created non-root user
# named "app" (UID 1654). Use it directly.
USER app

# ASP.NET Core 10 default HTTP port in official images
EXPOSE 8080

ENTRYPOINT ["dotnet", "CustomerKyc.Api.dll"]
